name: drawio2png

on:
  push:
    branches:
      - flow-scheme

jobs:
  drawio2png:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Export drawio file as pdf file
      uses: Burnett01/actions-drawio@1.2
      with:
        src: docs/flow_scheme.drawio
        dest: docs/flow_scheme.png
    - name: Add and commit PDF file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/flow_scheme.png
        git commit -m "Add PDF file"
    - name: Force push changes
      run: |
        git push origin HEAD:refs/heads/flow-scheme --force-with-lease
