name: drawio2pdf

on:
  push:
    branches:
      - flow-scheme
    paths:
      - "**.drawio"
      - "docs/*.drawio"
      - .github/workflows/drawio2pdf.yml

jobs:
  drawio2pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Export drawio file as pdf file
      uses: rlespinasse/drawio-export-action@v2
      with:
        format: pdf

    - name: Print git status
      run: |
        git status

    - name: Get author and committer info from HEAD commit
      uses: rlespinasse/git-commit-data-action@v1
      if: github.ref == 'refs/heads/flow-scheme'

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: sync draw.io exported files"
        commit_user_name: "GitHub Action"
        commit_user_email: "action@github.com"
      if: github.ref == 'refs/heads/flow-scheme'

    - name: Force push changes
      run: |
        git push origin HEAD:refs/heads/flow-scheme --force-with-lease
