name: drawio2pdf

on:
  push:
    branches:
      - flow-scheme

jobs:
  drawio2pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Export drawio file as pdf file
      uses: rlespinasse/drawio-export-action@v2.15.0
      with:
        input: docs/flow_scheme.drawio
        format: pdf
        output: docs/flow_scheme.pdf
    - name: Add and commit PDF file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/flow_scheme.pdf
        git commit -m "Add PDF file"
    - name: Force push changes
      run: |
        git push origin HEAD:refs/heads/flow-scheme --force-with-lease